CREATE TABLE IF NOT EXISTS Competitions(
    id int AUTO_INCREMENT PRIMARY KEY,
    name varchar(30) not null,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration int default 3,
    expires TIMESTAMP DEFAULT (DATE_ADD(CURRENT_TIMESTAMP, INTERVAL duration DAY)),
    current_reward int DEFAULT (starting_reward),
    starting_reward int DEFAULT 1,
    join_fee int DEFAULT 0,
    current_participants int default 0,
    min_participants int DEFAULT 3,
    paid_out tinyint default 0,
    min_score int DEFAULT 0,
    first_place_per float default 1,
    second_place_per float default 0.0,
    third_place_per float default 0.0,
    cost_to_create int default 1, 
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    check (starting_reward >= 1),
    check(join_fee >= 0)
    check (min_score >= 0),
    check (current_reward >= starting_reward),
    check (min_participants >= 3),
    check (current_participants >= 0),
)